project:
  type: website


# several branches can be specified here
branches:
  - branch: "release-0001"     # change this to the release branch
    output-dir: "0001"         # change this to year and month of the course instance

website:
  title: "SciLifeLab PULSE Training - Cohort 1"
  sidebar:
    style: "floating"
    background: "#F4F6F6"
    fontsize: 30px
    search: true
    contents: 
      - index.qmd 
      - GetStarted.qmd
      - TSTwebinars.qmd
      - "<details><summary>Sessions</summary>
          <ul>
            <li><a href='session1.qmd'>Session 1</a></li>
            <li><a href='session2.qmd'>Session 2</a></li>
            <li><a href='session3.qmd'>Session 3</a></li>
          </ul>
        </details>"
      - annualworkshop.qmd
      - "<details><summary>Sessions</summary>
          <ul>
            <li><a href='workshop-s1.qmd'>Beyond the Bench</a></li>
            <li><a href='workshop-s2.qmd'>Ethics for Future Leaders</a></li>
            <li><a href='workshop-s3.qmd'>Research Culture</a></li>
            <li><a href='workshop-s4.qmd'>Entrepreneurial Mindset</a></li>
          </ul>
        </details>"
  navbar:
    background: "#045c64"
    logo: "img/SciLifeLab_Logotype_NEG.png"
  favicon: "img/SciLifeLab_Logotype_NEG.png"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
