---
title: "SciLifeLab PULSE Training"
author: "PULSE Training & Career Development Committee"
date: today
---

::: {.callout-warning icon=false}

## Not just another postdoctoral program

PULSE has been specifically designed to connect early-career researchers with opportunities and skills that support long-term career sustainability across sectors. To meet this goal, the PULSE training program has been developed using the [European Competency Framework for Researchers (ResearchComp)](https://research-and-innovation.ec.europa.eu/jobs-research/researchcomp-european-competence-framework-researchers_en). As such, being or hosting a PULSE postdoc has specific requirements that differ from some traditional postdoctoral training programs.

>By the end of the PULSE program, all PULSE postdocs are expected to be able to demonstrate foundational to intermediate competencies in all ResearchComp areas, and advanced to expert competencies in at least one competency area of interest.

This website provides updated information as the PULSE Training program is deployed, and is intended primarily for PULSE postdoctoral fellows, but also for their group leaders, the PULSE consortium, and anyone who would like to follow the training!

:::


The PULSE Training & Career Development Committee can be reached at pulse.training@scilifelab.se

## Current status

We have just completed our first PULSE Annual Meeting -- thank you everyone for your engagement! Workshop materials are being uploaded to the website.

## Important Dates 

| Date | Event |
|----|----|
| May 22, 2026 | TST Webinar 3, 14:00 |
| March 20, 2026 | TST Webinar 2, 14:00 |
| March 10-13, 2026 | PULSE Annual Meeting - Uppsala |
|January 23, 2026 | First TST Webinar (afternoon, 14:00) |
: {tbl-colwidths="[30,70]"}

